language: go
install: true

go:
  - "1.16"

jobs:
  include:
    - os:
        - linux
        - osx
      script:
        - make test
        - make clean
    - os: windows
      script:
        - echo $SHELL